version: "3.9"
services:
   mysql:
      image: openzipkin/zipkin-mysql
      environment:
         - MYSQL_ROOT_PASSWORD=rootpassword
         - MYSQL_DATABASE=zipkin
         - MYSQL_USER=zipkin
         - MYSQL_PASSWORD=zipkin
  
   zipkin:
      image: openzipkin/zipkin
      environment:
        - STORAGE_TYPE=mysql
        - MYSQL_HOST=mysql
        - MYSQL_PASS=zipkin
      ports:
        - 9411:9411
      depends_on:
        - mysql

   producer: 
      image: ${DOCKER_REPO:-docker.io}/eos-boxed
      build: .
      command:
         - ./wait-for-it.sh 
         - zipkin:9411
         - --
         - nodeos 
         - --enable-stale-production 
         - --producer-name=eosio              
         - --plugin=eosio::producer_plugin  
         - --config-dir
         - /etc/eosio
         - --telemetry-url=http://zipkin:9411/api/v2/spans 
         - --telemetry-service-name=producer 
         - --telemetry-timeout-us=10000000
      depends_on:
         - zipkin
      
   ship:
      image: ${DOCKER_REPO:-docker.io}/eos-boxed
      build: .
      command:
         - ./wait-for-it.sh 
         - zipkin:9411
         - --
         - nodeos               
         - --plugin=eosio::state_history_plugin                                   
         - --trace-history 
         - --chain-state-history 
         - --disable-replay-opts 
         - --validation-mode=light 
         - --p2p-peer-address=producer:9876:blk
         - --state-history-endpoint=0.0.0.0:8080
         - --config-dir=/etc/eosio
         - --telemetry-url=http://zipkin:9411/api/v2/spans 
         - --telemetry-service-name=ship 
         - --telemetry-timeout-us=10000000
         - --send-mode=threaded_sync
      depends_on:
         - zipkin
         - producer

   rodeos:
      image: ${DOCKER_REPO:-docker.io}/eos-boxed
      build: .
      command: >
         /bin/sh -c "
            ./wait-for-it.sh zipkin:9411 ## do not use wait-for-it.sh to wait for ship:8080, it would cause the the websocket listening endpoint to be in unrecoverable state. 
            sleep 10   
            rodeos --clone-connect-to=ship:8080 --data-dir=/var/rodeos/data --rdb-threads=12 --telemetry-url=http://zipkin:9411/api/v2/spans --telemetry-service-name=rodeos --eos-vm-oc-cache-size-mb=200 --eos-vm-oc-compile-threads=8                 
         "       
      depends_on:
         - zipkin
         - ship

   bootstrap:
      image: ${DOCKER_REPO:-docker.io}/eos-boxed
      build: .
      command:
         - ./boot.sh 
      depends_on:
         - producer

