

version: "3.9"
services:
   jaeger-collector:
      image: jaegertracing/jaeger-collector
      command: ["--es.num-shards=1", "--es.num-replicas=0", "--es.server-urls=http://elasticsearch:9200", "--collector.zipkin.host-port=:9411"]
      ports:
        - "9411:9411"
      environment:
        - SPAN_STORAGE_TYPE=elasticsearch
        - ES_TAGS_AS_FIELDS_ALL=true
      restart: on-failure
      depends_on:
        - elasticsearch
  
   jaeger-query:
      image: jaegertracing/jaeger-query
      command: ["--es.num-shards=1", "--es.num-replicas=0", "--es.server-urls=http://elasticsearch:9200"]
      ports:
        - "16686:16686"
        - "16687"
      environment:
        - SPAN_STORAGE_TYPE=elasticsearch
        - ES_TAGS_AS_FIELDS_ALL=true
      restart: on-failure
      depends_on:
        - elasticsearch
  
   jaeger-agent:
      image: jaegertracing/jaeger-agent
      command: ["--reporter.grpc.host-port=jaeger-collector:14250", "--reporter.grpc.retry.max=1000"]
      ports:
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
      environment:
        - LOG_LEVEL=debug
      restart: on-failure
      depends_on:
        - jaeger-collector
  
   elasticsearch:
      container_name: es-container
      image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
      environment:
        - xpack.security.enabled=false
        - "discovery.type=single-node"
      ports:
        - 9200:9200

   producer: 
      image: ${EOS_IMAGE:-eos-boxed:latest}
      command:
         - ./wait-for-it.sh 
         - jaeger:9411
         - --
         - nodeos 
         - --enable-stale-production 
         - --producer-name=eosio              
         - --plugin=eosio::producer_plugin  
         - --config-dir
         - /etc/eosio
         - --telemetry-url=http://jaeger:9411/api/v2/spans 
         - --telemetry-service-name=producer 
      depends_on:
         - jaeger-collector
      
   ship:
      image: ${EOS_IMAGE:-eos-boxed:latest}
      command:
         - ./wait-for-it.sh 
         - jaeger-collector:9411
         - --
         - nodeos               
         - --plugin=eosio::state_history_plugin                                   
         - --trace-history 
         - --chain-state-history 
         - --disable-replay-opts 
         - --validation-mode=light 
         - --p2p-peer-address=producer:9876:blk
         - --state-history-endpoint=0.0.0.0:8080
         - --config-dir=/etc/eosio
         - --telemetry-url=http://jaeger-collector:9411/api/v2/spans 
         - --telemetry-service-name=ship 
         - --send-mode=threaded_sync
      depends_on:
         - jaeger-collector
         - producer

   rodeos:
      image: ${EOS_IMAGE:-eos-boxed:latest}
      command: >
         /bin/sh -c "
            ./wait-for-it.sh jaeger-collector:9411 ## do not use wait-for-it.sh to wait for ship:8080, it would cause the the websocket listening endpoint to be in unrecoverable state. 
            sleep 10   
            rodeos --clone-connect-to=ship:8080 --data-dir=/var/rodeos/data --rdb-threads=12 --telemetry-url=http://jaeger-collector:9411/api/v2/spans --telemetry-service-name=rodeos --eos-vm-oc-cache-size-mb=200 --eos-vm-oc-compile-threads=8                 
         "       
      depends_on:
         - jaeger-collector
         - ship

   bootstrap:
      image: ${EOS_IMAGE:-eos-boxed:latest}
      command:
         - ./boot.sh 
      depends_on:
         - producer

